import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry"
import Box  from "@mui/material/Box"
import Footer from "@/components/Footer"


export const metadata = {
  title: 'Turbo car rental management',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Box sx={{
              display: 'flex',
              flexDirection : 'column',
              minHeight: '100vh'
            }}
          >
            {children}
            <Footer/>
          </Box>
        </ ThemeRegistry>
      </body>
    </html>
  )
}
