import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry"

export const metadata = {
  title: 'Turbo car rental management',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          {children}
        </ ThemeRegistry>
      </body>
    </html>
  )
}
